version: '3'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: todo-app-front-dev
    ports: # VSCodeの拡張機能を使えば不要
      - 8080:8080 
    tty: true # コンテナの起動永続化
    volumes:
      - ./front:/usr/src/app
