version: '3'
services:

  # client
  client:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: todo-app-front
    ports:
      - 8080:8080
    tty: true # コンテナの起動永続化
    volumes:
      - ./front:/usr/src/app
